# Generated by Django 2.2.3 on 2019-07-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0020_auto_20190723_0722'),
        ('checkout', '0021_auto_20190719_2123'),
    ]

    operations = [
    ]
