# Generated by Django 2.2.3 on 2019-07-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0072_ordershipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipping',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordershipping',
            name='time_slot',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
